apiVersion: v1
kind: Pod
metadata:
  name: static-pod-test
spec:
  restartPolicy: Always
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 10000
    resources:
      requests:
        memory: 15Mi
      limits:
        memory: 15Mi
    readinessProbe:
      initialDelaySeconds: 2
      timeoutSeconds: 2
      periodSeconds: 5
      exec:
        command:
        - /bin/sh
        - -c
        - cat /tmp/healthy
